NoHandsAMI/NoHands

Lets_git.md

- resolves #3 
- Lets_git 작성해보았습니다.

feature: Lets_git 작성

---

packer_ami.json

- resolves #6 
- packer_ami.json 생성
- EC2 서버 띄운 후 수정 필요

feature: packer_ami.json 생성

---

playbook.yml

- resolves #10 
- jMeter playbook.yml 테스트용 생성

feature: jMeter playbook.yml 테스트용 생성

---

jmeter.log
roles/jmeter/files/run.sh
roles/jmeter/files/test_plan.jmx

- resolves #12 
- run.sh 생성
- jmx 시나리오 생성

test: jMeter 테스트

---

aws-ubuntu.pkr.hcl

- resolves #13 
- Packer 공식문서 기반 aws-ubuntu.pkr.hcl 문서 생성

feature: aws-ubuntu.prk.hcl 생성

---

.gitignore

- resolves #16 
- .gitignore 생성
-  jMeter.log 추가

feature: .gitignore 파일 jMeter.log 추가

---

.gitignore
scenario1/aws-ubuntu.pkr.hcl
scenario1/terminate_ec2.yml
scenario2/aws-ubuntu.pkr.hcl
scenario2/playbook.yml

- resolves #23 
- hcl 파일 수정
- jMeter 테스트
- 경로 수정 필요

feature: hcl 파일 수정 및 jMeter 테스트

---

roles/cloudwatch/files/amazon-cloudwatch-agent.json
roles/cloudwatch/tasks/main.yml

- resolves #18 
- ansible cloudwatch 설치 자동화
-  cloudwatch-agent 실행
-  agent 상태 확인
-

feature: cloudwatch - ansible yml 파일 생성

---

.gitignore
scenario1/aws-ubuntu.pkr.hcl
scenario1/aws-ubuntu.pkrvars.hcl

- resolves #24 
- scenario1 aws-ubuntu.pkrvars.hcl 환경변수 파일 생성 
- subnet_id, security_group_id, base_ami, instance_type, region 환경 변수 설정
- scenario2 유사 환경 변수 파일 필요

feature: pkrvars.hcl 환경 변수 파일 생성 

---

scenario2/aws-ubuntu.pkr.hcl
scenario2/playbook.yml

- resolves #29 
- scenario2/aws-ubuntu.pkr.hcl 수정

Refactor: scenario2/aws-ubuntu.pkr.hcl 수정

---

roles/common/httpd/tasks/install.yml
roles/jmeter/tasks/install.yml
scenario2/playbook.yml

- resolves #34 
- jMeter role에 java 11설치
- common/httpd role 추가

feature: Java, httpd role 추가

---

roles/common/apt/main.yml
roles/timezone/tasks/main.yml
roles/vars/main.yml

- resolves #28
- - common
- APT 캐시 업데이트 및 전체 패키지 업그레이드로 시스템을 최신 상태로 유지하고 보안 패치 반영
- upgrade: dist 는 필요한 경우 패키지를 제거하거나 새로 설치
- common packags는 필요한 공용 유틸리티 (curl,net-tools 등) 설치
- common packages는 vars에서 정의됨
- cloudwatch agent 시간 동기화 실패하지 않기 위해 ntp 삭제
- state: absent 하면 패키지를 제거하지만 설정 파일은 남길 수 있음
- purge: yes로 설정 파일까지 완전히 삭제
- vars
- curl : HTTP 요청 전송 툴, 외부에서 파일 받기 , API 호출 등에 자주 사용됨
- unzip : .zip 파일 압축 해제용. 배포 파일, 설정 파일 추출에 사용
- net-tools : ifconfig, netstat 등 네트워크 진단 도구 포함 (기본적으로 설치 안 됨)
- ca-certificates : HTTPS 인증서들을 시스템에 등록해주는 패키지, SSL 통신 시 필수
- gnupg : GPG 키를 이용한 서명/검증 도구, APT 저장소 인증이나 보안 키 등록에 필요

feature: common 디렉토리 작업

---

scenario2/aws-ubuntu.pkr.hcl

- resolves #38 
- roles/common 디렉터리 수정

Refactor: roles/common 디렉터리 수정

---

scenario2/aws-ubuntu.pkr.hcl
scenario2/playbook.yml

- resolves #41 
- playbook.yml 수정

Refactor: playbook.yml 수정

---

.gitignore
scenario2/aws-ubuntu.pkr.hcl

- resolves #36 
- scenario2 subnet_id, security_group_id 환경변수 설정
- scenario1, scenario2 pkrvars.hcl 환경변수 파일 생성

feature: pkrvars.hcl 생성

---

Dockerfile
monitor/docker-compose.yml
scenario1/playbook.yml
scenario2/aws-ubuntu.pkr.hcl

- resolves #32 
- Dockerfile 내 Packer, Ansible 설치
- Grafana docker-compose.yml 생성

feature: dockerfile 및 docker-compose 생성

---

.github/workflows/build.yml

- resolves #46 
- 각 시나리오별 Packer, Ansible 활용해 ami 생성 github actions workflow 추가 
- main에 push 될 때 자동 실행되도록 설정

feature: build.yml

---

roles/jmeter/files/run.sh
roles/jmeter/files/test_plan.jmx

- resolves #49 
- run.sh 수정
- t2.micro에 맞게 시나리오 수정

Refactor: jMeter 시나리오 수정

---

.github/workflows/build.yml
scenario1/aws-ubuntu.pkr.hcl

- resolves #48 
- pkrvars.hcl 제외 및 Github secrets에 환경변수로 추가
- scenario1 환경변수 수정

bug: build.yml

---

.github/workflows/build.yml

- resolves #52 
- 시나리오 별 환경변수 사용 분리

refactor: build.yml

---

.github/workflows/build.yml
scenario2/aws-ubuntu.pkr.hcl

- resolves #56 
- Packer init 추가

refactor: add init

---

roles/cloudwatch/templates/amazon-cloudwatch-agent.json.j2

- resolves #61 
- CloudWatch Log Group 분리

Refactor: CloudWatch Log Group 분리

---

roles/jmeter/files/run.sh

- resolves #65 
- jMeter run.sh 수정

Refactor: jMeter run.sh 수정

---

.github/workflows/build.yml
scenario1/aws-ubuntu.pkr.hcl
scenario1/playbook.yml
scenario2/aws-ubuntu.pkr.hcl
scenario2/playbook.yml

- resolves #67 
- 시나리오 별 환경변수 설정
- playbook 상대경로 변경

feature: log group vars

---

.github/workflows/build.yml

- resolves #69 
- scenario1 삭제
- 환경변수 분기 처리 삭제

feature: build scenario 2

---

roles/cloudwatch/tasks/install.yml

refactor: generate ami

---

.github/workflows/build.yml
scenario1/aws-ubuntu.pkr.hcl
scenario1/playbook.yml
scenario2/aws-ubuntu.pkr.hcl
scenario2/playbook.yml

- resolves #77 
- 시나리오 2 코드 전체 수정

refactor: change scenario 2

---

.github/workflows/build.yml
scenario1/aws-ubuntu.pkr.hcl
scenario1/playbook.yml

- resolves #85 
- scenario1 복원
- 디렉터리 구조 scenario2/* 수정

refactor: 디렉터리 구조 scenario2 변경

---

scenario2/ansible/playbook.yml
scenario2/ansible/roles/cloudwatch/templates/amazon-cloudwatch-agent.json.j2
scenario2/ansible/roles/httpd/tasks/main.yml
scenario2/scripts/rolling-update.sh

- resolves #87 
- apache2 설치
- index.html 웹 서버 생성
- 기존 asg 내 롤링 업데이트 진행 시 분기 처리

feature: apache2

---

scenario2/ansible/roles/httpd/tasks/main.yml

- resolves #90 
- httpd/tasks/main.yml 업데이트
- cpu load php script 생성
- php 및 의존성 설치

feature: cpu 부하 php 설치
